version: '3'
services:
  gateway:
    build: ./backend/gateway
    depends_on:
      - front
    env_file:
      - .env
    networks:
      - webapp
    ports:
      - 3001:3001
    restart: always
    container_name: gateway
    hostname: gateway

  database:
    build: ./backend/database
    ports:
      - "3000:3000"
    networks:
      - webapp
    restart: always
    container_name: database
    hostname: database

  front:
    build: ./frontend
    networks:
      - webapp
    ports:
      - 5000:5000
    restart: always
    container_name: front
    hostname: front

networks:
  webapp:
    driver: bridge

