version: '3'
services:
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - webapp
    ports:
      - 3000:3000
    volumes:
      - ./db:/app/db
    restart: always
    container_name: back
    hostname: back

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - back
    networks:
      - webapp
    ports:
      - 5000:5000
    restart: always
    container_name: front
    hostname: front

networks:
  webapp:
    driver: bridge

