version: '3'
services:
  back:
    build: ./backend
    networks:
      - webapp
    ports:
      - 3001:3001
    restart: always
    container_name: back
    hostname: back

  database:
    build: ./backend/database
    ports:
      - "3000:3000"
    networks:
      - webapp
    restart: always
    container_name: database
    hostname: database

  front:
    build: ./frontend
    depends_on:
      - back
    networks:
      - webapp
    ports:
      - 5000:5000
    restart: always
    container_name: front
    hostname: front

networks:
  webapp:
    driver: bridge

