version: '3'
services:
  gateway:
    build: ./backend/gateway
    depends_on:
      - front
      - database
      - authentication
    env_file:
      - .env
    networks:
      - webapp
    ports:
      - 3001:3001
    restart: always
    container_name: gateway
    hostname: gateway

  authentication:
    build: ./backend/authentication
    ports:
      - "3002:3002"
    networks:
      - webapp
    restart: always
    container_name: authentication
    hostname: authentication

  database:
    build: ./backend/database
    ports:
      - "3000:3000"
    networks:
      - webapp
    depends_on:
     - authentication
    container_name: database
    hostname: database
    volumes:
     - ./database:/app/database

  front:
    build: ./frontend
    networks:
      - webapp
    ports:
      - 5000:5000
    restart: always
    container_name: front
    hostname: front

networks:
  webapp:
    driver: bridge

